---
title: Benchmarking Methodology
---

## End-to-End Benchmarks

The end-to-end benchmarks capture the user experience in response to different actions. The suite of benchmarks included in this cookbook are designed to inform how the choice of Zarr versions and chunking schemes influence the user experience.

### End-to-End Benchmarks: Datasets


### End-to-End Benchmarks: Approach

CarbonPlan's [benchmark-maps](https://github.com/carbonplan/benchmark-maps) repository leverages [Playwright](https://playwright.dev/python/) for the end-to-end performance benchmarks. By default, the benchmarks are run on [https://prototype-maps.vercel.app/](https://prototype-maps.vercel.app/) although the url is configurable. The frame below shows this domain after selecting an approach, Zarr version, and dataset.

The benchmarking script takes the following steps:

1. Launch chromium browser 
2. Create a new page
3. Start chromium tracing
4. Select Zarr version in the dropdown
5. Select Dataset in the dropbown
6. Wait 5 seconds for the page the render
7. Zoom in a defined number of times, waiting 5 seconds after each action
8. Write out metadata about each run and the trace record

The frame rate and request information are extracted from the resultant metadata and trace records. The completion time for each zoom level is determined by comparing the screen captures in the trace record to the expected result for each zoom level.


```{=html}
<iframe
  style='transform: scale(0.5); transform-origin: top left;'
  id="inlineFrameExample"
  title="Inline Frame Example"
  width="1440"
  height="1055"
  src="https://prototype-maps.vercel.app/direct-client/v2/1MB-chunks"
>
</iframe>
```

