---
title: Prototype Deployment
---

## `prototype-maps`

We started the [prototype-maps](https://github.com/carbonplan/prototype-maps) project to support visualizing Zarr data using multiple approaches in a consolidated application. The project is currently deployed at [https://prototype-maps.vercel.app/](https://prototype-maps.vercel.app/). Only the dynamic client approach is currently live, although the tiling approach will be [added shortly](https://github.com/carbonplan/prototype-maps/pull/7). The current version of the dynamic client page includes the option to select from several different datasets. Datasets are available in either Zarr V2 or Zarr V3 format, with different projections (equirectangular or mercator), chunking schemes (~1MB/chunk, ~5MB/chunk, ~10MB/chunk, or ~25MB/chunk), and sharding schemes (none, ~50MB/shard, ~100MB/shard). The time slider allows scrolling through the two years of daily data included in this demonstration. Options for adjusting the color mapping and visualizing time series are included in drop-down windows, with the spatial selector allowing custom selection of the data window averaged for the time series.

```{=html}
<iframe
  style='transform: scale(0.5); transform-origin: top left; margin-bottom: -450px; margin-right: -720px;'
  id="Dynamic-Client-Selection"
  title="Prototype Maps - Dynamic Client"
  width="1440"
  height="900"
  src="https://prototype-maps.vercel.app/"
>
</iframe>
```

## `prototype-maps`: Technology stack

The prototype deployment was built using [@carbonplan/maps](https://github.com/carbonplan/maps) with different configurations of `projection` and Zarr `version`, for which support was added in `3.1.0`. Upstream, the `@carbonplan/maps` library depends on `zarr-js@3.3.0`, for support reading Zarr in v3 and sharded formats as well as `mapbox-gl@1.13.1` for the mapping context in which the Zarr data are rendered.
